pipeline {
    agent any

    tools{
      maven 'maven 3.9.8'	
    }
    
    stages{
        stage('build'){
            steps{
                echo 'compiling worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo 'running unit tests on worker app'
                }
            }
        stage('package'){
            steps{
                echo 'packaging worker app'
            }
        }
    }
    post{
        always{
            echo 'lding multibranch pipeline for worker is completed'
    }
  }
}
