pipeline {
    agent any

    tools{
      maven 'maven 3.9.8'	
    }
    
    stages{
        stage('build'){
            steps{
                echo 'compiling worker app'
                dir('worker'){
                  sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                echo 'Running Unit Tests on worker app...'
                dir('worker'){
                  sh 'mvn clean test'
                  }
            }
        stage('package'){
            steps{
                echo 'packaging worker app...'
		dir('worker'){
		  sh 'mvn package'
	  	  }	
                }
            }
        }
   }   
    post{
        always{
            echo 'lding multibranch pipeline for worker is completed'
    }
  }
}
